INSERT OR IGNORE INTO manufacturers (company_name)
VALUES 
    ('Sony'),
    ('Nintendo'),
    ('Microsoft'),
    ('Sega'),
    ('SNK Corp'),
    ('PC');

INSERT OR IGNORE INTO platforms (platform_name, manufacturer_id)
VALUES
    ('Playstation',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sony')),
    ('Playstation 2',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sony')),
    ('Playstation 3',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sony')),
    ('Playstation 4',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sony')),
    ('Playstation 5',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sony')),
    ('PSP',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sony')),
    ('PS Vita',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sony')),

    ('NES',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),
    ('Game Boy',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),
    ('Super Nintendo',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),
    ('N64',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),
    ('Game Cube',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),
    ('DS',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),
    ('WII',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),
    ('3DS',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),
    ('WII U',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),
    ('Switch',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),
    ('Switch 2',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Nintendo')),

    ('XBox',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Microsoft')),
    ('XBox 360',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Microsoft')),
    ('XBox ONE',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Microsoft')),
    ('XBox Series X/S',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Microsoft')),

    ('Master System',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sega')),
    ('Game Gear',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sega')),
    ('Mega Drive',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sega')),
    ('Saturn',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sega')),
    ('Dreamcast',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'Sega')),

    ('Neo Geo',
    (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'SNK Corp')),

    ('PC',
        (SELECT manufacturer_id FROM manufacturers WHERE company_name = 'PC'));